# Generated by Django 5.1.4 on 2025-01-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_pwresetattempt'),
        ('video', '0002_comment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='watched_videos', to='app_users.appuser'),
        ),
    ]
