# Generated by Django 5.1.4 on 2025-01-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_watched_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='airing_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='casting',
        ),
        migrations.RemoveField(
            model_name='video',
            name='director',
        ),
        migrations.RemoveField(
            model_name='video',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='video',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='video',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
