# Generated by Django 5.1.5 on 2025-01-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_remove_video_airing_date_remove_video_casting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tmdb_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('tmdb_id', 'type')},
        ),
    ]
