# Generated by Django 5.1.4 on 2025-01-26 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_alter_video_last_watched_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='last_watched_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
