# Generated by Django 5.1.4 on 2025-02-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_remove_video_torrent_remove_video_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='bm_sub_file_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='en_sub_file_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='torrent_file_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
