# Generated by Django 5.1.4 on 2025-02-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_remove_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='bm_sub_file_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='en_sub_file_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='torrent_file_name',
            field=models.CharField(max_length=100),
        ),
    ]
