# Generated by Django 5.1.4 on 2025-03-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_alter_video_bm_sub_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='bm_sub_file_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='en_sub_file_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='overview',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='video',
            name='torrent_file_name',
            field=models.CharField(max_length=1000),
        ),
    ]
