# Generated by Django 5.1.4 on 2025-01-03 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_alter_appuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PwResetAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pw_reset', to='app_users.appuser')),
            ],
        ),
    ]
