# Generated by Django 5.1.4 on 2025-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_pwresetattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
