# Generated by Django 5.1.4 on 2025-02-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_appuser_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='prefered_stream_dimensions',
            field=models.PositiveIntegerField(choices=[(0, 'SMALL'), (1, 'MEDIUM'), (2, 'LARGE')], default=1),
        ),
    ]
